In [108]:
import pandas as pd
import numpy as np

from datetime import datetime, timedelta

dataPath = "../../Data/"

In [109]:
Ottawa_Weather_2020 = pd.read_csv(dataPath+"DailyWeather/OttawaIntAirport2020.csv")
York_Weather_2020 = pd.read_csv(dataPath+"DailyWeather/NorthYork2020.csv")
Ottawa_Weather_2021 = pd.read_csv(dataPath+"DailyWeather/OttawaIntAirport2021.csv")
York_Weather_2021 = pd.read_csv(dataPath+"DailyWeather/NorthYork2021.csv")
# frames = [Ottawa_Weather, York_Weather, Peel_Weather]
frames = [Ottawa_Weather_2020, York_Weather_2020,Ottawa_Weather_2021,York_Weather_2021]
Weather_dimension = pd.concat(frames)
# Weather_dimension["Station Name"] = Weather_dimension["Station Name"].map(lambda x: "Ottawa" if (x=="OTTAWA INTL A") else "Toronto")
# Weather_dimension = Weather_dimension.drop(columns=['B', 'C'])
Weather_dimension = Weather_dimension[(Weather_dimension["Date/Time"] < "2021-03-01") & (Weather_dimension["Date/Time"] >= "2020-11-01")]
Weather_dimension = Weather_dimension.drop(columns=['Max Temp Flag', 'Min Temp Flag', 'Min Temp Flag', 'Mean Temp Flag', 'Heat Deg Days Flag', 'Data Quality', 'Cool Deg Days Flag', 'Total Precip Flag', 'Dir of Max Gust (10s deg)', 'Dir of Max Gust Flag', 'Spd of Max Gust (km/h)', 'Spd of Max Gust Flag'])

In [110]:
Weather_dimension["Station Name"].drop_duplicates()

305         OTTAWA INTL A
305    TORONTO NORTH YORK
Name: Station Name, dtype: object

In [111]:
precipArray = Weather_dimension["Total Precip (mm)"].values
for i in range(3,len(precipArray)):
    if (np.isnan(precipArray[i])):
        precipArray[i] = round(sum(precipArray[i-3:i])/3,1)
Weather_dimension["Total Precip (mm)"] = precipArray

maxArray = Weather_dimension["Max Temp (°C)"].values
for i in range(3,len(maxArray)):
    if (np.isnan(maxArray[i])):
        maxArray[i] = round(sum(maxArray[i-3:i])/3,1)
Weather_dimension["Max Temp (°C)"] = maxArray

minArray = Weather_dimension["Min Temp (°C)"].values
for i in range(3,len(minArray)):
    if (np.isnan(minArray[i])):
        minArray[i] = round(sum(minArray[i-3:i])/3,1)
Weather_dimension["Min Temp (°C)"] = minArray






tmpArray = Weather_dimension["Mean Temp (°C)"].values
for i in range(3,len(tmpArray)):
    if (np.isnan(tmpArray[i])):
        tmpArray[i] = round(sum(tmpArray[i-3:i])/3,1)
Weather_dimension["Mean Temp (°C)"] = tmpArray

tmpArray = Weather_dimension["Heat Deg Days (°C)"].values
for i in range(3,len(tmpArray)):
    if (np.isnan(tmpArray[i])):
        tmpArray[i] = round(sum(tmpArray[i-3:i])/3,1)
Weather_dimension["Heat Deg Days (°C)"] = tmpArray

tmpArray = Weather_dimension["Cool Deg Days (°C)"].values
for i in range(3,len(tmpArray)):
    if (np.isnan(tmpArray[i])):
        tmpArray[i] = round(sum(tmpArray[i-3:i])/3,1)
Weather_dimension["Cool Deg Days (°C)"] = tmpArray

tmpArray = Weather_dimension["Total Rain (mm)"].values
for i in range(3,len(tmpArray)):
    if (np.isnan(tmpArray[i])):
        tmpArray[i] = round(sum(tmpArray[i-3:i])/3,1)
Weather_dimension["Total Rain (mm)"] = tmpArray

tmpArray = Weather_dimension["Total Snow (cm)"].values
for i in range(3,len(tmpArray)):
    if (np.isnan(tmpArray[i])):
        tmpArray[i] = round(sum(tmpArray[i-3:i])/3,1)
Weather_dimension["Total Snow (cm)"] = tmpArray


tmpArray = Weather_dimension["Snow on Grnd (cm)"].values
tmpArray[0] = 0.
for i in range(4,len(tmpArray)):
    if (np.isnan(tmpArray[i])):
        tmpArray[i] = round(sum(tmpArray[i-3:i])/3,1)
Weather_dimension["Snow on Grnd (cm)"] = tmpArray

In [112]:
Weather_dimension["Total Precip (mm)"].isna().sum()

0

In [113]:
Weather_dimension["Max Temp (°C)"].isna().sum()

0

In [114]:
Weather_dimension["Min Temp (°C)"].isna().sum()

0

In [115]:
Weather_dimension.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Rain Flag,Total Snow (cm),Total Snow Flag,Total Precip (mm),Snow on Grnd (cm),Snow on Grnd Flag
305,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-01,2020,11,1,7.8,-0.7,3.6,14.4,0.0,2.2,NaN,0.0,NaN,2.2,0.0,NaN
306,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-02,2020,11,2,2.0,-2.5,-0.3,18.3,0.0,0.0,NaN,3.7,NaN,2.4,0.0,T
307,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-03,2020,11,3,0.3,-4.1,-1.9,19.9,0.0,0.0,NaN,0.0,T,0.0,3.0,NaN
308,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-04,2020,11,4,13.8,-3.0,5.4,12.6,0.0,0.0,NaN,0.0,NaN,0.0,3.0,NaN
309,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-05,2020,11,5,19.3,-1.2,9.1,8.9,0.0,0.0,NaN,0.0,NaN,0.0,2.0,NaN

In [116]:
Weather_dimension["Snow on Grnd Flag"] = Weather_dimension["Snow on Grnd (cm)"] != 0
Weather_dimension["Snow on Grnd Flag"] = Weather_dimension["Snow on Grnd Flag"].map(lambda x: "Yes" if x else "No")
Weather_dimension["Total Rain Flag"] = Weather_dimension["Total Rain (mm)"] != 0
Weather_dimension["Total Rain Flag"] = Weather_dimension["Total Rain Flag"].map(lambda x: "Yes" if x else "No")
Weather_dimension["Total Snow Flag"] = Weather_dimension["Total Snow (cm)"] != 0
Weather_dimension["Total Snow Flag"] = Weather_dimension["Total Snow Flag"].map(lambda x: "Yes" if x else "No")

In [117]:
# (Weather_dimension["Snow on Grnd Flag"] == True).sum()

In [118]:
Weather_dimension.shape

(240, 20)

In [119]:
# Weather_dimension = Weather_dimension[['Longitude (x)', 'Latitude (y)', 'Station Name', 'Climate ID', 'Date/Time',
#        'PROVINCE_CODE', 'LOCAL_YEAR', 'LOCAL_MONTH', 'LOCAL_DAY','MEAN_TEMPERATURE',  'MIN_TEMPERATURE',
#        'MAX_TEMPERATURE', 
#        'TOTAL_PRECIPITATION',  'TOTAL_RAIN',
#         'TOTAL_SNOW', 'DIRECTION_MAX_GUST', 
#        'SPEED_MAX_GUST', 'COOLING_DEGREE_DAYS',
#       'HEATING_DEGREE_DAYS']]
# Weather_dimension = Weather_dimension[["Longitude (x)","Latitude (y)","Station Name","Climate ID","Date/Time",
#         "Year","Month","Day","Max Temp (°C)","Min Temp (°C)",
#  "Mean Temp (°C)","Heat Deg Days (°C)","Cool Deg Days (°C)","Total Rain (mm)","Total Snow (cm)",
#  "Total Precip (mm)"]]

Weather_dimension.insert(0, "surrogate_key",  np.arange(len(Weather_dimension)))
# Weather_dimension = Weather_dimension.dropna() TODO
# Weather_dimension["Date/Time"] = pd.to_datetime(Weather_dimension["Date/Time"] ).dt.strftime('%Y-%m-%d')

In [120]:
Weather_dimension.to_csv("Weather_dimension.csv",index=False)
Weather_dimension.head()

,surrogate_key,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Max Temp (°C),...,Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Rain Flag,Total Snow (cm),Total Snow Flag,Total Precip (mm),Snow on Grnd (cm),Snow on Grnd Flag
305,0,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-01,2020,11,1,7.8,...,3.6,14.4,0.0,2.2,Yes,0.0,No,2.2,0.0,No
306,1,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-02,2020,11,2,2.0,...,-0.3,18.3,0.0,0.0,No,3.7,Yes,2.4,0.0,No
307,2,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-03,2020,11,3,0.3,...,-1.9,19.9,0.0,0.0,No,0.0,No,0.0,3.0,Yes
308,3,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-04,2020,11,4,13.8,...,5.4,12.6,0.0,0.0,No,0.0,No,0.0,3.0,Yes
309,4,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-05,2020,11,5,19.3,...,9.1,8.9,0.0,0.0,No,0.0,No,0.0,2.0,Yes

In [121]:
Weather_dimension.shape

(240, 21)

In [122]:
Weather_dimension.isna().sum()

surrogate_key         0
Longitude (x)         0
Latitude (y)          0
Station Name          0
Climate ID            0
Date/Time             0
Year                  0
Month                 0
Day                   0
Max Temp (°C)         0
Min Temp (°C)         0
Mean Temp (°C)        0
Heat Deg Days (°C)    0
Cool Deg Days (°C)    0
Total Rain (mm)       0
Total Rain Flag       0
Total Snow (cm)       0
Total Snow Flag       0
Total Precip (mm)     0
Snow on Grnd (cm)     0
Snow on Grnd Flag     0
dtype: int64

In [123]:
Weather_dimension["Station Name"].drop_duplicates()

305         OTTAWA INTL A
305    TORONTO NORTH YORK
Name: Station Name, dtype: object

In [124]:
Weather_dimension.head()

,surrogate_key,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Max Temp (°C),...,Mean Temp (°C),Heat Deg Days (°C),Cool Deg Days (°C),Total Rain (mm),Total Rain Flag,Total Snow (cm),Total Snow Flag,Total Precip (mm),Snow on Grnd (cm),Snow on Grnd Flag
305,0,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-01,2020,11,1,7.8,...,3.6,14.4,0.0,2.2,Yes,0.0,No,2.2,0.0,No
306,1,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-02,2020,11,2,2.0,...,-0.3,18.3,0.0,0.0,No,3.7,Yes,2.4,0.0,No
307,2,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-03,2020,11,3,0.3,...,-1.9,19.9,0.0,0.0,No,0.0,No,0.0,3.0,Yes
308,3,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-04,2020,11,4,13.8,...,5.4,12.6,0.0,0.0,No,0.0,No,0.0,3.0,Yes
309,4,-75.67,45.32,OTTAWA INTL A,6106001,2020-11-05,2020,11,5,19.3,...,9.1,8.9,0.0,0.0,No,0.0,No,0.0,2.0,Yes